Adds YouTube links to the call format documents
BitcoinDesign/Meta pull request #88
Opened 2021-03-12 09:45 UTC by GBKS

Since we now have a YouTube channel where we upload call recordings, this should be pointed out in the documents for call formats.

@ConorOkus I only added it to the community call document. Let me know if you also want me to update the design review doc.

2021-03-12 11:02 UTC, johnsBeharry commented on Community-Calls.md
> +We use [Jitsi](https://jitsi.org), which is open-source, privacy-preserving, and available as web and desktop applications.
```suggestion
We use [Jitsi](https://jitsi.org), which is open-source, doesn't require you to create an account, and is available as web and desktop applications.
```

2021-03-12 11:06 UTC, johnsBeharry requested changes
just managing expectations wrt the privacy preserving part. at the end of the day it's a public forum, and a hosted service.

2021-03-12 14:54 UTC, ConorOkus commented
Thanks @GBKS . Think it makes sense to add to Design Review as well.

2021-03-22 07:22 UTC, Bosch-0 submitted a review, later dismissed
ACK from me

2021-03-23 01:47 UTC, Bosch-0 approved these changes
Fresh ACK from me

2021-03-23 08:12 UTC, johnsBeharry approved these changes

2021-03-23 08:13 UTC, merged